all:
  vars:
    ansible_user: uli
  hosts:
  children:
    monitors:
      hosts:
        ceph-mon-[1:3].hq.staerkindustries.com
    osds:
      hosts:
        ceph-osd-[1:4].hq.staerkindustries.com
    gws:
      hosts:
        ceph-gw.hq.staerkindustries.com
