- name: distribute ceph keyring on all ceph nodes
  ansible.posix.authorized_key:
    user: uli
    state: present
    key: "{{ lookup('file', 'ceph.pub') }}"
  become: true

# disable wifi and bluetooth, restart if needed
- name: disable wifi and bluetooth on all nodes
  ansible.builtin.blockinfile:
    path: "/boot/firmware/config.txt"
    block: |
      [all]
      dtoverlay=disable-wifi
      dtoverlay=disable-bt
  become: true
  notify: reboot

- name: remove usercfg.txt if present
  ansible.builtin.file:
    path: "/boot/firmware/usercfg.txt"
    state: absent
  become: true
  notify: reboot
